<Move>
  <name>Acid</name>
  <type>POISON</type>
  <PP>30</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>SPECIAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>40</power>
	  </Damage>
	  <Chance>
	    <chance>10</chance>
		<effect>
	      <StatEffect>
	        <target>target</target>
		    <stat>Sdefense</stat>
		    <levels>-1</levels>
	      </StatEffect>
		</effect>
	  </Chance>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>