<Move>
  <name>Blizzard</name>
  <type>ICE</type>
  <PP>5</PP>
  <accuracy>70</accuracy>
  <speed>0</speed>
  <DT>SPECIAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>120</power>
	  </Damage>
	  <Chance>
	    <chance>10</chance>
		<effect>
		  <StatusEffect>
			<target>target</target>
			<status>Freeze</status>
		  </StatusEffect>
		</effect>
	  </Chance>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>