<Move>
  <name>Bonemerang</name>
  <type>GROUND</type>
  <PP>10</PP>
  <accuracy>90</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Multihit>
	    <attack>
		  <power>50</power>
		</attack>
		<min>2</min>
		<max>2</max>
	  </Multihit>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>