<Move>
  <name>Clamp</name>
  <type>WATER</type>
  <PP>20</PP>
  <accuracy>0</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <StaticDamage>
	    <pDamage>true</pDamage>
		<percent>6</percent>
	  </StaticDamage>
    </effect>
  </effect>
  <isContact>true</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>false</canMiss>
</Move>