<Move>
  <name>Constrict</name>
  <type>NORMAL</type>
  <PP>35</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>10</power>
	  </Damage>
	  <Chance>
	    <chance>10</chance>
		<effect>
		  <StatEffect>
			<target>target</target>
			<stat>speed</stat>
			<levels>-1</levels>
		  </StatEffect>
		</effect>
	  </Chance>
    </effect>
  </effect>
  <isContact>true</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>