<Move>
  <name>Disable</name>
  <type>NORMAL</type>
  <PP>20</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>NONE</DT>
  <effect>
    <require>
	  <CheckLastMove>
	    <valid>true</valid>
	  </CheckLastMove>
	  <CheckEnemy>
	    <disabled>true</disabled>
	  </CheckEnemy>
	</require>
    <effect>
	  <SetFlag>
	    <target>target</target>
		<flag>isDisabled</flag>
		<text>$target's $lastMove has been disabled!</text>
	  </SetFlag>
	  <SetCounter>
	    <target>target</target>
		<counter>DisableCounter</counter>
		<type>random</type>
		<min>4</min>
		<max>7</max>
	  </SetCounter>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>true</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>