<Move>
  <name>Haze</name>
  <type>ICE</type>
  <PP>30</PP>
  <accuracy>0</accuracy>
  <speed>0</speed>
  <DT>NONE</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <ClearStats>
	    <target>target</target>
	  </ClearStats>
	  <ClearStats>
	    <target>user</target>
		<text>A haze clears all stat effects</text>
	  </ClearStats>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>false</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>false</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>false</canMiss>
</Move>