<Move>
  <name>Hyper Beam</name>
  <type>NORMAL</type>
  <PP>5</PP>
  <accuracy>90</accuracy>
  <speed>0</speed>
  <DT>SPECIAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>150</power>
	  </Damage>
	  <SetFlag>
	    <target>user</target>
		<flag>isCharging</flag>
	  </SetFlag>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>