<Move>
  <name>Mega Kick</name>
  <type>NORMAL</type>
  <PP>5</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
		<power>120</power>
	  </Damage>
    </effect>
  </effect>
  <isContact>true</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>