<Move>
  <name>Pin Missile</name>
  <type>BUG</type>
  <PP>20</PP>
  <accuracy>85</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Multihit>
	    <attack>
		  <power>14</power>
		</attack>
		<min>2</min>
		<max>5</max>
	  </Multihit>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>