<Move>
  <name>Psywave</name>
  <type>PSYCHIC</type>
  <PP>15</PP>
  <accuracy>80</accuracy>
  <speed>0</speed>
  <DT>SPECIAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <LevelDamage>
	    <random>true</random>
		<max>15</max>
		<min>5</min>
	  </LevelDamage>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>