<Move>
  <name>Rolling Kick</name>
  <type>FIGHTING</type>
  <PP>15</PP>
  <accuracy>85</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>60</power>
	  </Damage>
	  <Chance>
	    <chance>30</chance>
		<effect>
		  <SetFlag>
			<target>target</target>
			<flag>isFlinching</flag>
		  </SetFlag>
		</effect>
	  </Chance>
    </effect>
  </effect>
  <isContact>true</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>