<Move>
  <name>Skull Bash</name>
  <type>NORMAL</type>
  <PP>15</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <SetFlag>
	    <target>user</target>
		<flag>MultiTurnMove</flag>
		<text>$target is charging up!</text>
	  </SetFlag>
	  <SetCounter>
	    <target>user</target>
	    <counter>MultiTurnCounter</counter>
	    <type>set</type>
	    <n>1</n>
	  </SetCounter>
	  <StatEffect>
	    <target>user</target>
		<stat>defense</stat>
		<levels>1</levels>
	  </StatEffect>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>false</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>false</canMiss>
</Move>