<Move>
  <name>SmokeScreen</name>
  <type>NORMAL</type>
  <PP>20</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>NONE</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <StatEffect>
	    <target>target</target>
		<stat>accuracy</stat>
		<levels>-1</levels>
	  </StatEffect>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>true</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>