<Move>
  <name>Swords Dance</name>
  <type>NORMAL</type>
  <PP>30</PP>
  <accuracy>0</accuracy>
  <speed>0</speed>
  <DT>NONE</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <StatEffect>
	    <target>user</target>
		<stat>attack</stat>
		<levels>2</levels>
	  </StatEffect>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>false</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>true</isSnatchable>
  <isMirrorable>false</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>false</canMiss>
</Move>