<Move>
  <name>Thunder Punch</name>
  <type>ELECTRIC</type>
  <PP>15</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>75</power>
	  </Damage>
	  <Chance>
	    <chance>10</chance>
		<effect>
		  <StatusEffect>
			<target>target</target>
			<status>Paralysis</status>
		  </StatusEffect>
		</effect>
	  </Chance>
    </effect>
  </effect>
  <isContact>true</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>true</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>