<Move>
  <name>Toxic</name>
  <type>POISON</type>
  <PP>10</PP>
  <accuracy>90</accuracy>
  <speed>0</speed>
  <DT>NONE</DT>
  <effect>
    <require/>
    <effect>
      <StatusEffect>
        <target>target</target>
        <status>Toxic</status>
      </StatusEffect>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>true</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>