<Move>
  <name>Tri Attack</name>
  <type>NORMAL</type>
  <PP>10</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>SPECIAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Damage>
	    <power>80</power>
	  </Damage>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>