<Move>
  <name>Twineedle</name>
  <type>BUG</type>
  <PP>20</PP>
  <accuracy>100</accuracy>
  <speed>0</speed>
  <DT>PHYSICAL</DT>
  <effect>
    <require>
	</require>
    <effect>
	  <Multihit>
	    <attack>
		  <power>25</power>
		</attack>
		<min>2</min>
		<max>2</max>
	  </Multihit>
	  <Chance>
	    <chance>20</chance>
		<effect>
		  <StatusEffect>
			<target>target</target>
			<status>Poison</status>
		  </StatusEffect>
		</effect>
	  </Chance>
	  <Chance>
	    <chance>20</chance>
		<effect>
		  <StatusEffect>
			<target>target</target>
			<status>Poison</status>
		  </StatusEffect>
		</effect>
	  </Chance>
    </effect>
  </effect>
  <isContact>false</isContact>
  <isProtectable>true</isProtectable>
  <isReflectable>false</isReflectable>
  <isSnatchable>false</isSnatchable>
  <isMirrorable>true</isMirrorable>
  <isPunch>false</isPunch>
  <isSound>false</isSound>
  <canMiss>true</canMiss>
</Move>